# Generated by Django 5.2.5 on 2025-08-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveBigIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='myapp.language')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
